apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummysite
  labels:
    app: dummysite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummysite
  template:
    metadata:
      labels:
        app: dummysite
    spec:
      containers:
        - name: dummysite
          image: 192.168.68.101:8082/dummysite:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
      imagePullSecrets:
        - name: nexus-secret    
