name: Build and Push Docker Image to Nexus

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create local certs directory and save Nexus CA
        run: |
          mkdir -p .github/certs/your-nexus-domain.com
          cat << 'EOF' > .github/certs/your-nexus-domain.com/ca.crt
          -----BEGIN CERTIFICATE-----
          PASTE_YOUR_ACTUAL_NEXUS_CA_CERTIFICATE_HERE
          -----END CERTIFICATE-----
          EOF  
      - name: Create BuildKit config
        run: |
          mkdir -p .github
          cat <<EOF > .github/buildkitd.toml
          [registry."${{ secrets.NEXUS_REPO_URL }}"]
            ca=["/etc/docker/certs.d/${{ secrets.NEXUS_REPO_URL }}/ca.crt"]
          EOF

      - name: Log in to Nexus Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NEXUS_REPO_URL }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.NEXUS_REPO_URL }}/dummysite-${{ github.run_number }}:latest          